### PR TITLE
fix: remove deprecated sonar.login and replace with sonar.token

### PR DESCRIPTION
**Pull request by matthiasbaldi**
Issue: #61

- replace sonar.login with sonar.token

TODO:
- not yet buildet this pkg
- not yet tested with a current sonar version

### CODE REVIEW

**Review by yassin-kammoun-sonarsource — CHANGES_REQUESTED** [review]
Hey @matthiasbaldi,

Many thanks for your contribution!

Unfortunately, you will need to adjust the scope of your contribution. Although the property `sonar.login` is indeed deprecated, SonarQube users are still using it. Therefore, this npm package should keep supporting it as long as SonarQube does. However, we are indeed missing the support for `sonar.token`.

Let's do the following then:

- Let's leave unchanged the support for `sonar.login`
- Let's add the support for `sonar.token`

**Comment by matthiasbaldi** [comment]
Sure makes sense.
I think you ment to add just both values, right?
Because the token property is used a long time ago for the public lib api.

**Comment by yassin-kammoun-sonarsource** [comment]
Adding both values won't really solve the problem because the warning will still be printed for users using SonarQube 10+. Not sure what's the best course of action here.

Let me clarify this and come back to you.

**Comment by yassin-kammoun-sonarsource** [comment]
Hey @matthiasbaldi,

After clarifying the matter, adding both values wouldn't work as you would expect because the warning would still pop up. As a result, we should have distinct support for both "sonar.login" and "sonar.token" and leave users to choose which one to use depending on the SonarQube version. I opened this [PR](https://github.com/SonarSource/sonar-scanner-npm/pull/69) to address that accordingly. I also cherry-picked your initial commit so that your contribution is accounted for :).

Thanks for the contribution!

**Pull request closed without merging**
