### PR TITLE
Fix PR coverage

### PR DESCRIPTION
**Pull request by vdiez**

### CODE REVIEW

**Review by ilia-kebets-sonarsource — CHANGES_REQUESTED** [review]
As discussed, could you please add a comment about why you do that (it's a fork) and where is the solution taken from (cirrus docs)

**Comment by vdiez** [comment]
done! :)

**Review by ilia-kebets-sonarsource — APPROVED** [review]
LGTM! Good Job!

**Review by ilia-kebets-sonarsource — APPROVED** [review]
LGTM

**Pull request merged**
